apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yyhncj36c-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/yyhncj36c-java-quarkus-gitops